"""create quick logs table

Revision ID: 312364f85d52
Revises: 3be061344626
Create Date: 2026-09-16 20:26:07.340065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312364f85d52'
down_revision = '3be061344626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('xp_awarded >= 0', name='ck_quick_log_xp_awarded_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quick_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quick_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quick_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quick_logs_user_id'))

    op.drop_table('quick_logs')
    # ### end Alembic commands ###
