"""create finance settings and commitments

Revision ID: 79fc9b6dfde4
Revises: a9d93433904b
Create Date: 2026-09-11 22:23:24.548244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fc9b6dfde4'
down_revision = 'a9d93433904b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_finance_commitment_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finance_commitments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_commitments_user_id'), ['user_id'], unique=False)

    op.create_table('finance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('protected_savings', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payday_first', sa.Integer(), nullable=False),
    sa.Column('payday_second', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('payday_first <> payday_second', name='ck_finance_settings_paydays_different'),
    sa.CheckConstraint('payday_first BETWEEN 1 AND 31', name='ck_finance_settings_payday_first_valid'),
    sa.CheckConstraint('payday_second BETWEEN 1 AND 31', name='ck_finance_settings_payday_second_valid'),
    sa.CheckConstraint('protected_savings >= 0', name='ck_finance_settings_protected_savings_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # Backfill FinanceSettings for existing users.
    op.execute(sa.text("INSERT INTO finance_settings (user_id, current_balance, protected_savings, payday_first, payday_second, created_at, updated_at) SELECT u.id, 0.00, 0.00, 15, 30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM users AS u WHERE NOT EXISTS (SELECT 1 FROM finance_settings AS fs WHERE fs.user_id = u.id)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_settings')
    with op.batch_alter_table('finance_commitments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_commitments_user_id'))

    op.drop_table('finance_commitments')
    # ### end Alembic commands ###
