"""create user progress table

Revision ID: a9d93433904b
Revises: 75ed75d7656f
Create Date: 2026-09-11 21:54:36.376459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d93433904b'
down_revision = '75ed75d7656f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('level >= 1', name='ck_user_progress_level_positive'),
    sa.CheckConstraint('total_xp >= 0', name='ck_user_progress_total_xp_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )

    # Backfill: cria o progresso inicial para usuários existentes.
    op.execute(sa.text("""
        INSERT INTO user_progress
            (user_id, total_xp, level, rank, created_at, updated_at)
        SELECT
            u.id,
            0,
            1,
            'E',
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        FROM users AS u
        WHERE NOT EXISTS (
            SELECT 1
            FROM user_progress AS up
            WHERE up.user_id = u.id
        )
    """))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_progress')
    # ### end Alembic commands ###
