"""create workout tables

Revision ID: b0ad8e34d9dc
Revises: 0926dc54bdc5
Create Date: 2026-09-12 20:17:59.655527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ad8e34d9dc'
down_revision = '0926dc54bdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('pull', 'push', 'core', 'legs', 'skill', 'mobility', 'other')", name='ck_workout_exercise_category'),
    sa.CheckConstraint('order_index >= 0', name='ck_workout_exercise_order_nonnegative'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_exercises_session_id'), ['session_id'], unique=False)

    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds > 0', name='ck_workout_set_duration_positive'),
    sa.CheckConstraint('reps IS NOT NULL OR duration_seconds IS NOT NULL', name='ck_workout_set_has_metric'),
    sa.CheckConstraint('reps IS NULL OR reps > 0', name='ck_workout_set_reps_positive'),
    sa.CheckConstraint('set_number > 0', name='ck_workout_set_number_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['workout_exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'set_number', name='uq_workout_set_exercise_number')
    )
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sets_exercise_id'), ['exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sets_exercise_id'))

    op.drop_table('workout_sets')
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_exercises_session_id'))

    op.drop_table('workout_exercises')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))

    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
